name: main
on:
  workflow_dispatch:
    inputs:
      release_version:
        description: version to release
        required: true
        type: string
jobs:
  build:
    name: build
    strategy:
      matrix:
        GOOS: [ linux, darwin ]
        GOARCH: [ arm, arm64, amd64 ]
        exclude:
          - GOOS: darwin
            GOARCH: arm
    runs-on: ubuntu-latest
    env:
      executable: victoria-metrics-${{ matrix.GOOS }}-${{ matrix.GOARCH }}
    steps:
      - name: Code checkout
        uses: actions/checkout@v4

      - name: Setup Go
        id: go
        uses: actions/setup-go@v5
        with:
          go-version: stable
          cache: false

      - name: Cache Go artifacts
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
            ~/go/bin
          key: go-artifacts-${{ runner.os }}-crossbuild-${{ steps.go.outputs.go-version }}-${{ hashFiles('go.sum', 'Makefile', 'app/**/Makefile') }}
          restore-keys: go-artifacts-${{ runner.os }}-crossbuild-

      - name: Build
        run: |
          export PATH=$PATH:$(go env GOPATH)/bin # temporary fix. See https://github.com/actions/setup-go/issues/14
          make ${{env.executable}}

      - name: Create or update release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: bin/${{env.executable}}
          tag: ${{inputs.release_version}}
          commit: master
          token: ${{ secrets.GITHUB_TOKEN }}
