name: main
on:
  workflow_dispatch:
    inputs:
      release_version:
        description: version to release
        required: true
        type: string
jobs:
  build:
    name: Build
    strategy:
      matrix:
        GOOS: [ linux, darwin ]
        GOARCH: [ arm, arm64, amd64 ]
        exclude:
          - GOOS: darwin
            GOARCH: arm
    runs-on: ubuntu-latest
    env:
      executable: victoria-metrics-${{ matrix.GOOS }}-${{ matrix.GOARCH }}
    steps:
      - name: Setup Go
        uses: actions/setup-go@main
        with:
          go-version: 1.19.3
        id: go
      - name: Code checkout
        uses: actions/checkout@master
      - name: Dependencies
        run: |
          make install-golint
          make install-errcheck
          make install-golangci-lint
      - name: Build
        run: |
          export PATH=$PATH:$(go env GOPATH)/bin # temporary fix. See https://github.com/actions/setup-go/issues/14
          make ${{env.executable}}

      - name: Create or update release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: bin/${{env.executable}}
          tag: ${{inputs.release_version}}
          commit: master
          token: ${{ secrets.GITHUB_TOKEN }}