name: main
on:
  push:
    tags:
      - 'v*'
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go
        uses: actions/setup-go@main
        with:
          go-version: 1.19.1
        id: go
      - name: Code checkout
        uses: actions/checkout@master
      - name: Dependencies
        run: |
          make install-golint
          make install-errcheck
          make install-golangci-lint
      - name: Build
        run: |
          export PATH=$PATH:$(go env GOPATH)/bin # temporary fix. See https://github.com/actions/setup-go/issues/14
          make victoria-metrics-linux-arm
          
      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          # This token is provided by Actions, you do not need to create your own token
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{github.ref}}
          release_name: ${{github.ref}}

      - name: Upload linux-arm
        uses: actions/upload-release-asset@v1
        env:
          # This token is provided by Actions, you do not need to create your own token
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: bin/victoria-metrics-linux-arm
          asset_name: victoria-metrics-linux-arm
          asset_content_type: application/octet-stream

